-- DaktarSab Health Modules Migration
-- PHASE 9: MARKETPLACE & PARTNER ROUTING
-- PHASE 10: UNIVERSAL HEALTH RECORD (UHR)
-- PHASE 11: DOCTOR'S VIRTUAL CHAMBER (RX WRITER)
-- PHASE 12: USER REVIEW SYSTEM

-- 1. Update Profiles with Role
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('patient', 'doctor', 'admin');
    END IF;
END $$;

ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS role user_role DEFAULT 'patient';

-- 2. Update Doctors and Hospitals with Verification status
ALTER TABLE public.doctors 
ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);

ALTER TABLE public.hospitals 
ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT false;

-- 3. Reviews Table
CREATE TABLE IF NOT EXISTS public.reviews (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    reviewer_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    provider_id UUID NOT NULL, -- Doctor UUID or Hospital UUID
    provider_type TEXT NOT NULL CHECK (provider_type IN ('doctor', 'hospital')),
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Medical Records Table (UHR)
CREATE TABLE IF NOT EXISTS public.medical_records (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('summary', 'prescription', 'record', 'lab_report')),
    content_data JSONB,
    file_url TEXT,
    doctor_id UUID REFERENCES auth.users(id), -- Optional: if generated by a doctor
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Prescriptions Table
CREATE TABLE IF NOT EXISTS public.prescriptions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    doctor_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    patient_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    rx_json JSONB NOT NULL,
    pdf_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- SECURITY: Row Level Security (RLS)

-- Reviews SECURITY
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Reviews are public" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Users can insert reviews" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = reviewer_id);

-- Medical Records SECURITY
ALTER TABLE public.medical_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Patients can view their own records" 
ON public.medical_records FOR SELECT 
USING (auth.uid() = patient_id OR auth.uid() = doctor_id);

CREATE POLICY "Patients can manage their own records" 
ON public.medical_records FOR ALL 
USING (auth.uid() = patient_id);

CREATE POLICY "Doctors can create records for patients" 
ON public.medical_records FOR INSERT 
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE user_id = auth.uid() AND role = 'doctor'
    )
);

-- Prescriptions SECURITY
ALTER TABLE public.prescriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Patients and Doctors can view prescriptions" 
ON public.prescriptions FOR SELECT 
USING (auth.uid() = patient_id OR auth.uid() = doctor_id);

CREATE POLICY "Doctors can create prescriptions" 
ON public.prescriptions FOR INSERT 
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE user_id = auth.uid() AND role = 'doctor'
    )
);

-- Storage Bucket setup should be done via Supabase Dashboard/CLI, 
-- but we can document the policy requirements here for the user.
