// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Workaround to prevent LockManager timeout errors during Vite HMR
const globalForSupabase = globalThis as unknown as {
  supabase: ReturnType<typeof createClient<Database>> | undefined;
};

// Extremely robust fix for the Supabase Vite HMR deadlock:
// If a hot-reload strands a promise holding the lock, all future requests (and other tabs) hang for 10s.
// This mock intercepts ONLY the Supabase auth lock and executes it instantly without actually freezing across tabs.
if (typeof navigator !== 'undefined' && navigator.locks && navigator.locks.request) {
  const originalRequest = navigator.locks.request.bind(navigator.locks);
  navigator.locks.request = function (name: string, options: any, callback?: any) {
    if (name.includes('auth-token') || name.includes('supabase')) {
      const cb = typeof options === 'function' ? options : callback;
      return cb();
    }
    return originalRequest(name, options, callback);
  } as any;
}

export const supabase = 
  globalForSupabase.supabase ??
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });

if (import.meta.env.DEV) {
  globalForSupabase.supabase = supabase;
}